# Generated by Django 4.0.4 on 2022-06-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('send_schedule_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
