# Generated by Django 4.0.4 on 2022-06-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
